### PR TITLE
Improving Windows support for writing hosts file entries.

### PR DESCRIPTION
**Pull request by bpearson**
Improving Windows support for writing to the host files by handling the line endings before writing the file.

### CODE REVIEW

**Comment by bpearson** [comment]
Mentioned in Issue #171 before writing to the host file, convert the line endings. Requires Ruby 1.9

**Comment by seth-reeser** [comment]
This was not working consistently for me - will need to further test and adapt.

**Comment by bpearson** [comment]
Strange, it was for me. What environment are you using? Was it happening in a particular way? What did you experience?

**Comment by tschirmer** [comment]
There there any progress on testing on this one? We want to use this but we can't without this bug being patched

**Comment by seth-reeser** [comment]
@tschirmer what version of Windows are you using?

**Comment by tschirmer** [comment]
@seth-reeser Windows 10

**Comment by seth-reeser** [comment]
This will only work for the host, we'll be releasing a solution that will write CRLF to both the host and guest where appropriate.

**Comment by seth-reeser** [comment]
This has been resolved with v1.8.6

**Pull request closed without merging**
